---
- include_tasks: "{{ role_path }}/tasks/{{ ansible_network_os }}-get-version.yml"

- set_fact:
    net_compare_version: "{{ net_version_list[ansible_network_os] }}"

- debug: msg="{{ net_version_system }} < {{ net_compare_version }}"
  when: net_version_system | version_compare(net_compare_version, '<')
  changed_when: net_version_system | version_compare(net_compare_version, '<')
